In [1]:
conda install -c conda-forge opencv

^C

Note: you may need to restart the kernel to use updated packages.


In [2]:
conda update -n base -c defaults conda


^C

Note: you may need to restart the kernel to use updated packages.


In [3]:
pip install --upgrade imutils

^C
Note: you may need to restart the kernel to use updated packages.


In [1]:
# import the necessary packages
# import the necessary packages
from collections import deque
from imutils.video import VideoStream
import numpy as np
import argparse
import cv2
import imutils
import time
import os

#construct the argument parse and parse the arguments
#ap = argparse.ArgumentParser()
#ap.add_argument("-v", "--video",
#	help="path to the (optional) video file")
#ap.add_argument("-b", "--buffer", type=int, default=64,
#	help="max buffer size")
#args = vars(ap.parse_args())

In [11]:
# define the lower and upper boundaries of the "green"
# ball in the HSV color space, then initialize the
# list of tracked points
greenLower = (29, 86, 6)
greenUpper = (64, 255, 255)
#blueLower = (,86,6)
#blueUpper = (30,255,255)
pts = deque()
#eraser = deque()

vs = cv2.VideoCapture(0)
# otherwise, grab a reference to the video file
size = (int(vs.get(3)),int(vs.get(4)))
result = cv2.VideoWriter('filename.avi',  
                         cv2.VideoWriter_fourcc(*'MJPG'), 
                         10, size) 
    
# allow the camera or video file to warm up
time.sleep(2.0)
# keep looping
while True:
	# grab the current frame
	ret, frame = vs.read()
	# handle the frame from VideoCapture or VideoStream
	# if we are viewing a video and we did not grab a frame,
	# then we have reached the end of the video
	if frame is None:
		break
	# resize the frame, blur it, and convert it to the HSV
	# color space
	#frame = imutils.resize(frame, width=600)
	blurred = cv2.GaussianBlur(frame, (11, 11), 0)
	hsv = cv2.cvtColor((blurred), cv2.COLOR_BGR2HSV)
	# construct a mask for the color "green", then perform
	# a series of dilations and erosions to remove any small
	# blobs left in the mask
	mask = cv2.inRange(hsv, greenLower, greenUpper)
	mask = cv2.erode(mask, None, iterations=2)
	mask = cv2.dilate(mask, None, iterations=2)
 # find contours in the mask and initialize the current
	# (x, y) center of the ball
	cnts = cv2.findContours(mask.copy(), cv2.RETR_EXTERNAL,
		cv2.CHAIN_APPROX_SIMPLE)
	cnts = imutils.grab_contours(cnts)
	center = None
	# only proceed if at least one contour was found
	if len(cnts) > 0:
		# find the largest contour in the mask, then use
		# it to compute the minimum enclosing circle and
		# centroid
		c = max(cnts, key=cv2.contourArea)
		((x, y), radius) = cv2.minEnclosingCircle(c)
		M = cv2.moments(c)
		center = (int(M["m10"] / M["m00"]), int(M["m01"] / M["m00"]))
		# only proceed if the radius meets a minimum size
		if radius > 10:
			# draw the circle and centroid on the frame,
			# then update the list of tracked points
			cv2.circle(frame, (int(x), int(y)), int(radius),
				(0, 255, 255), 2)
			cv2.circle(frame, center, 5, (0, 0, 255), -1)
	# update the points queue
	pts.appendleft(center)
 	# loop over the set of tracked points
	for i in range(1, len(pts)):
		# if either of the tracked points are None, ignore
		# them
		if pts[i - 1] is None or pts[i] is None:
			continue
		# otherwise, compute the thickness of the line and
		# draw the connecting lines
		thickness = 10
		cv2.line(frame, pts[i - 1], pts[i], (0, 0, 255), thickness)
	# show the frame to our screen
	cv2.imshow("Frame", cv2.flip(frame,1))
	result.write(cv2.flip(frame,1)) 
	key = cv2.waitKey(1) & 0xFF
	# if the 'q' key is pressed, stop the loop
	if key == ord("q"):
		break
# if we are not using a video file, stop the camera video stream

vs.release()
result.release() 
# close all windows
cv2.destroyAllWindows()

In [20]:
green = np.uint8([[[42,209,228 ]]])
hsv_green = cv2.cvtColor(green,cv2.COLOR_BGR2HSV)
print (hsv_green)

[[[ 27 208 228]]]


In [21]:
0.82*255

209.1

In [30]:
0.89*20

17.8

In [31]:
green = np.uint8([[[228,42,42 ]]])
hsv_green = cv2.cvtColor(green,cv2.COLOR_BGR2HSV)
print (hsv_green)

[[[120 208 228]]]


In [34]:
blue = np.uint8([[[19,33,240]]])
hsv = cv2.cvtColor(blue,cv2.COLOR_BGR2HSV)
print (hsv)

[[[  2 235 240]]]


In [35]:
blue = np.uint8([[[19,240,233]]])
hsv = cv2.cvtColor(blue,cv2.COLOR_BGR2HSV)
print (hsv)

[[[ 31 235 240]]]


In [37]:
blue = np.uint8([[[19,218,240]]])
hsv = cv2.cvtColor(blue,cv2.COLOR_BGR2HSV)
print (hsv)

[[[ 27 235 240]]]


In [38]:
vs.stop()

In [39]:
vs.release()

AttributeError: 'WebcamVideoStream' object has no attribute 'release'

In [11]:
# define the lower and upper boundaries of the "green"
# ball in the HSV color space, then initialize the
# list of tracked points
greenLower = (29, 86, 6)
greenUpper = (64, 255, 255)
blueLower = (20,80,240)
blueUpper = (30,255,255)
pts = deque()


vs = cv2.VideoCapture(0)
# otherwise, grab a reference to the video file

# allow the camera or video file to warm up
time.sleep(2.0)
# keep looping
while True:
	# grab the current frame
	ret,frame = vs.read()
	# handle the frame from VideoCapture or VideoStream
	# if we are viewing a video and we did not grab a frame,
	# then we have reached the end of the video
	if frame is None:
		break
	# resize the frame, blur it, and convert it to the HSV
	# color space
	#frame = imutils.resize(frame, width=600)
	blurred = cv2.GaussianBlur(frame, (11, 11), 0)
	hsv = cv2.cvtColor(blurred, cv2.COLOR_BGR2HSV)
    
    
	# construct a mask for the color "green", then perform
	# a series of dilations and erosions to remove any small
	# blobs left in the mask
	mask = cv2.inRange(hsv, greenLower, greenUpper)
	mask = cv2.erode(mask, None, iterations=2)
	mask = cv2.dilate(mask, None, iterations=2)
 # find contours in the mask and initialize the current
	# (x, y) center of the ball
	cnts = cv2.findContours(mask.copy(), cv2.RETR_EXTERNAL,
		cv2.CHAIN_APPROX_SIMPLE)
	cnts = imutils.grab_contours(cnts)
	center = None
	# only proceed if at least one contour was found
	if len(cnts) > 0:
		# find the largest contour in the mask, then use
		# it to compute the minimum enclosing circle and
		# centroid
		c = max(cnts, key=cv2.contourArea)
		((x, y), radius) = cv2.minEnclosingCircle(c)
		M = cv2.moments(c)
		center = (int(M["m10"] / M["m00"]), int(M["m01"] / M["m00"]))
		# only proceed if the radius meets a minimum size
		if radius > 10:
			# draw the circle and centroid on the frame,
			# then update the list of tracked points
			cv2.circle(frame, (int(x), int(y)), int(radius),
				(0, 255, 255), 2)
			cv2.circle(frame, center, 5, (0, 0, 255), -1)
	# update the points queue
	pts.appendleft(center)
    
	#now about the eraser
	# resize the frame, blur it, and convert it to the HSV
	# color space
	#frame = imutils.resize(frame, width=600)
	#blurred_eraser = cv2.GaussianBlur(frame, (11, 11), 0)
	#hsv = cv2.cvtColor(blurred, cv2.COLOR_BGR2HSV)
	# construct a mask for the color "green", then perform
	# a series of dilations and erosions to remove any small
	# blobs left in the mask
	mask_e = cv2.inRange(hsv, blueLower, blueUpper)
	mask_e = cv2.erode(mask_e, None, iterations=2)
	mask_e = cv2.dilate(mask_e, None, iterations=2)
 # find contours in the mask and initialize the current
	# (x, y) center of the ball
	cnts_e = cv2.findContours(mask_e.copy(), cv2.RETR_EXTERNAL,
		cv2.CHAIN_APPROX_SIMPLE)
	cnts_e = imutils.grab_contours(cnts_e)
	center_e = None
	# only proceed if at least one contour was found
	if len(cnts_e) > 0:
		# find the largest contour in the mask, then use
		# it to compute the minimum enclosing circle and
		# centroid
		c_e = max(cnts_e, key=cv2.contourArea)
		((x_e, y_e), radius_e) = cv2.minEnclosingCircle(c_e)
		M_e = cv2.moments(c_e)
		center_e = (int(M_e["m10"] / M_e["m00"]), int(M_e["m01"] / M_e["m00"]))
		# only proceed if the radius meets a minimum size
		if radius_e > 10:
			# draw the circle and centroid on the frame,
			# then update the list of tracked points
			cv2.circle(frame, (int(x_e), int(y_e)), int(radius_e),
				(25, 255, 255), 2)
			cv2.circle(frame, center, 5, (0, 0, 255), -1)        
	if center in pts:
		pts.remove(center)        #erasing the point
 	# loop over the set of tracked points
	for i in range(1, len(pts)):
		# if either of the tracked points are None, ignore
		# them
		if pts[i - 1] is None or pts[i] is None:
			continue
		# otherwise, compute the thickness of the line and
		# draw the connecting lines
		thickness = 10
		cv2.line(frame, pts[i - 1], pts[i], (0, 0, 255), thickness)
	# show the frame to our screen
	cv2.imshow("Frame", cv2.flip(frame,1))
	key = cv2.waitKey(1) & 0xFF
	# if the 'q' key is pressed, stop the loop
	if key == ord("q"):
		break
# if we are not using a video file, stop the camera video stream

vs.release()

# close all windows
cv2.destroyAllWindows()

In [48]:
green = np.uint8([[[164,240,240]]])
hsv_green = cv2.cvtColor(green,cv2.COLOR_BGR2HSV)
print (hsv_green)


[[[ 30  81 240]]]


In [51]:
green = np.uint8([[[0,177,253]]])
hsv_green = cv2.cvtColor(green,cv2.COLOR_BGR2HSV)
print (hsv_green)


[[[ 21 255 253]]]
